id: unidexgrasp
name: Unidexgrasp
asset_dir: ${oc.env:FLUXSTEER_DATA_ROOT,./data}/UniDexGrasp
checkpoint: checkpoints/fluxsteer/fluxsteer_unidexgrasp.pth
inference:
  steps: 75
  mc_samples: 200
  temperature: 0.05
  w_erf: 0.4
  w_spf: 0.4
  w_srf: 0.4
